### ISSUE TITLE
Runtime comparisons

### ISSUE THREAD

**Issue by bkj** [wouterkool/attention-learn-to-route#1]
Really enjoy the paper -- have you done any comparisons between the runtimes of your method and other heuristic solvers (either learned or unlearned)?  In Table 2, you should you can get a better quality solution than OR-Tools, but are the runtimes comparable?  Would they be comparable as instance size grew?

Thanks
Ben

**Comment by ldy8665** [comment]
I think Python 3.5 is not enough when running the `run.py`.It occurs such errors

> attention_model.py", line 26  node_embeddings: torch.Tensor 
> SyntaxError: invalid syntax. 

And Class syntax for NamedTuple is only supported in Python 3.6+

**Comment by wouterkool** [comment]
Thanks, I have updated the readme!
