### ISSUE TITLE
Question about training VRP model.

### ISSUE THREAD

**Issue by Tangarff** [wouterkool/attention-learn-to-route#12]
Hello, I tried to training vrp model, I changed the tsp commend, used the command "**python run.py --graph_size 20 --baseline rollout --run_name 'vrp20_rollout' --val_dataset data/vrp/vrp20_validation_seed4321.pkl** " to trained vrp model.
But the terminal showed "an ValueError: expected sequence of length 2 at dim 1 (got 20)", could you please tell me how to trained vrp model?

**Comment by chaitjo** [comment]
Refer to the `options.py` file. You must set the flag `--problem` to the problem you'd like to run on. E.g. the default value is `tsp`, hence you have an error.

**Comment by wouterkool** [comment]
I'm assuming your problem is solved so closing this issue.
