### ISSUE TITLE
Hello,how does the gif(tsp.gif) in the code be generated.

### ISSUE THREAD

**Issue by sakfjoagh** [wouterkool/attention-learn-to-route#15]
It looks like I didn`t get it from the results of the quick start.
Waiting for your answer,thanks.

**Comment by wouterkool** [comment]
The gif should be generated using https://github.com/wouterkool/attention-learn-to-route/blob/master/simple_tsp.ipynb

**Comment by sakfjoagh** [comment]
Thanks,very helpful.
