### ISSUE TITLE
Default value for embed_dim in MultiHeadAttention class will cause an error.

### ISSUE THREAD

**Issue by ahmad-PH** [wouterkool/attention-learn-to-route#22]
@wouterkool 
if you don't provide the `embed_dim` parameter when instantiating a `MultiHeadAttention` object, you will get the following error when trying to invoke its `forward` method:
`AttributeError: 'MultiHeadAttention' object has no attribute 'W_out'`. 
This is due to this piece of code in the constructor:
```
if embed_dim is not None:
    self.W_out = nn.Parameter(torch.Tensor(n_heads, key_dim, embed_dim))
```
which will mean you have no `W_out` if `embed_dim` was None.

**Comment by wouterkool** [comment]
Thanks! I figured it was best to not make embed_dim optional in the end.
