### ISSUE TITLE
AssertionError in 'State_tsp.py'

### ISSUE THREAD

**Issue by zhangjw-THU** [wouterkool/attention-learn-to-route#42]
When I'm run the 'run.py', there is always a assert error:

 torch.is_tensor(key) or isinstance(key, slice)  # If tensor, idx all tensors by this tensor

please help me! Thanks!

**Comment by wouterkool** [comment]
Hi! Have you tried Python 3.8?

**Comment by zhangjw-THU** [comment]
ooooooh! 
It's python version error!
Thanks!
