### ISSUE TITLE
Beamsearch vs Sampling

### ISSUE THREAD

**Issue by chaitjo** [wouterkool/attention-learn-to-route#7]
Hi, thanks for the code! Could you briefly describe the difference between Sampling from the policy and your beamsearch implementation?

**Comment by wouterkool** [comment]
Sorry this one got out of my view, but I'll answer for future reference.

When sampling, you choose the next node according to the probabilities one at a time. When doing this in a batch, you generate `k` independent samples. The result may contain duplicates.

With beam search, starting from the empty route, you select the top `k` from all possible extensions by one node, then you extend those and take again the top `k` according to the log-probability of the solution created so far, etc. The results are `k` good different routes but they may be similar and are not samples.
