### ISSUE TITLE
the implementation of BatchNorm maybe have a mistake

### ISSUE THREAD

**Issue by obitolyz** [wouterkool/attention-learn-to-route#8]
Thinks for your code. i have a question about the implementation of BN. In 140th line of graph_encoder.py, "self.normalizer(input.view(-1, input.size(-1))).view(*input.size())", u merge batch_size and node_size, but i think the last dimension is node_size.  input = input.permute(0, 2, 1).
pls help me.

**Comment by wouterkool** [comment]
Hi!

There may be some ambiguity in `node_size`, so let's describe the size of `input` as `[batch_size, graph_size, hidden_dim]`, e.g. `[512, 20, 128]` for a batch of 512 instances with 20 graph nodes, where each node in each graph has a 128 dimensional representation / 128 hidden neurons.

The `input` is first reshaped to `[batch_size * graph_size, hidden_dim]` and then BatchNorm is applied, such that the activations for each of the `hidden_dim` = 128 neurons get normalized across both the instances in the batch and the nodes in the graph. After that, they are transformed back to the original shape.
